# Telling brownie to grap the env vars stored in the '.env' file
dotenv: .env

dependencies:
  # - <organisation/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@0.3.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.0'

networks:
  default: development
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  development:
    verify: False
  ganache-local-1:
    verify: False
