# Telling brownie to grap the env vars stored in the '.env' file
dotenv: .env

# Compiler & Dependencies
dependencies:
  # - <organisation/repo>@<version>
  - OpenZeppelin/openzeppelin-contracts@4.4.2
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.2'

# Networks variables
networks:
  # default: mainnet-fork-dev
  # Test networks
  kovan:
    weth_token: '0xd0a1e359811322d97991e03f863a0c30c2cf029c'
    dai_token: '0xFf795577d9AC8bD7D90Ee22b6C1703490b6512FD'
    aave_lp_address_provider : '0x88757f2f99175387aB4C6a4b3067c77A695b0349'
    dai_eth_price_feed: '0x22B58f1EbEDfCA50feF632bD73368b2FdA96D541'
  # Forked mainnets
  mainnet-fork-dev:
    weth_token: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2'
    dai_token: '0x6b175474e89094c44da98b954eedeac495271d0f'
    aave_lp_address_provider : '0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5'
    dai_eth_price_feed: '0x773616E4d11A78F511299002da57A0a94577F1f4'